### ISSUE TITLE
Error: TypeError: speech.processExpression is not a function

### ISSUE THREAD

**Issue by lukejanicke** [kgryte/tex-equation-to-svg#2]
After installing globally, I keep getting this error,
```
~/Documents $ tex2svg 'ax^2+bx+c=0.

Error: TypeError: speech.processExpression is not a function
    at GetSpeech (/usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax-node/lib/mj-single.js:540:29)
    at Function.execute (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:348:50)
~/Documents $ 
```

**Comment by lukejanicke** [comment]
My typo at the end of that command. Correct syntax still throws the error.

```
~/Documents $ tex2svg 'ax^2+bx+c=0'
Error: TypeError: speech.processExpression is not a function
    at GetSpeech (/usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax-node/lib/mj-single.js:540:29)
    at Function.execute (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/tex-equation-to-svg/node_modules/mathjax/unpacked/MathJax.js:348:50)
~/Documents $ 
```

**Comment by kgryte** [comment]
Would you mind performing an `npm ls` on the package's node module dependencies? In particular, I am interested in knowing the installed mathjax version number. It is possible that somehow a breaking change occurred in mathjax which did not follow semver.

**Comment by wodeni** [comment]
+1. Have the same error. Here is the output of `npm ls`:
```
└─┬ tex-equation-to-svg@1.0.1
  ├─┬ mathjax-node@0.5.2
  │ ├─┬ jsdom@7.2.2
  │ │ ├── abab@1.0.4
  │ │ ├── acorn@2.7.0
  │ │ ├─┬ acorn-globals@1.0.9
  │ │ │ └── acorn@2.7.0 deduped
  │ │ ├── cssom@0.3.2
  │ │ ├─┬ cssstyle@0.2.37
  │ │ │ └── cssom@0.3.2 deduped
  │ │ ├─┬ escodegen@1.9.1
  │ │ │ ├── esprima@3.1.3
  │ │ │ ├── estraverse@4.2.0
  │ │ │ ├── esutils@2.0.2
  │ │ │ ├─┬ optionator@0.8.2
  │ │ │ │ ├── deep-is@0.1.3
  │ │ │ │ ├── fast-levenshtein@2.0.6
  │ │ │ │ ├─┬ levn@0.3.0
  │ │ │ │ │ ├── prelude-ls@1.1.2 deduped
  │ │ │ │ │ └── type-check@0.3.2 deduped
  │ │ │ │ ├── prelude-ls@1.1.2
  │ │ │ │ ├─┬ type-check@0.3.2
  │ │ │ │ │ └── prelude-ls@1.1.2 deduped
  │ │ │ │ └── wordwrap@1.0.0
  │ │ │ └── source-map@0.6.1
  │ │ ├── nwmatcher@1.4.4
  │ │ ├── parse5@1.5.1
  │ │ ├─┬ request@2.87.0
  │ │ │ ├── aws-sign2@0.7.0
  │ │ │ ├── aws4@1.7.0
  │ │ │ ├── caseless@0.12.0
  │ │ │ ├─┬ combined-stream@1.0.6
  │ │ │ │ └── delayed-stream@1.0.0
  │ │ │ ├── extend@3.0.1
  │ │ │ ├── forever-agent@0.6.1
  │ │ │ ├─┬ form-data@2.3.2
  │ │ │ │ ├── asynckit@0.4.0
  │ │ │ │ ├── combined-stream@1.0.6 deduped
  │ │ │ │ └── mime-types@2.1.18 deduped
  │ │ │ ├─┬ har-validator@5.0.3
  │ │ │ │ ├─┬ ajv@5.5.2
  │ │ │ │ │ ├── co@4.6.0
  │ │ │ │ │ ├── fast-deep-equal@1.1.0
  │ │ │ │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ │ │ │ └── json-schema-traverse@0.3.1
  │ │ │ │ └── har-schema@2.0.0
  │ │ │ ├─┬ http-signature@1.2.0
  │ │ │ │ ├── assert-plus@1.0.0
  │ │ │ │ ├─┬ jsprim@1.4.1
  │ │ │ │ │ ├── assert-plus@1.0.0 deduped
  │ │ │ │ │ ├── extsprintf@1.3.0
  │ │ │ │ │ ├── json-schema@0.2.3
  │ │ │ │ │ └─┬ verror@1.10.0
  │ │ │ │ │   ├── assert-plus@1.0.0 deduped
  │ │ │ │ │   ├── core-util-is@1.0.2 deduped
  │ │ │ │ │   └── extsprintf@1.3.0 deduped
  │ │ │ │ └─┬ sshpk@1.14.2
  │ │ │ │   ├── asn1@0.2.3
  │ │ │ │   ├── assert-plus@1.0.0 deduped
  │ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
  │ │ │ │   │ └── tweetnacl@0.14.5 deduped
  │ │ │ │   ├─┬ dashdash@1.14.1
  │ │ │ │   │ └── assert-plus@1.0.0 deduped
  │ │ │ │   ├─┬ ecc-jsbn@0.1.1
  │ │ │ │   │ └── jsbn@0.1.1 deduped
  │ │ │ │   ├─┬ getpass@0.1.7
  │ │ │ │   │ └── assert-plus@1.0.0 deduped
  │ │ │ │   ├── jsbn@0.1.1
  │ │ │ │   ├── safer-buffer@2.1.2
  │ │ │ │   └── tweetnacl@0.14.5
  │ │ │ ├── is-typedarray@1.0.0
  │ │ │ ├── isstream@0.1.2
  │ │ │ ├── json-stringify-safe@5.0.1
  │ │ │ ├─┬ mime-types@2.1.18
  │ │ │ │ └── mime-db@1.33.0
  │ │ │ ├── oauth-sign@0.8.2
  │ │ │ ├── performance-now@2.1.0
  │ │ │ ├── qs@6.5.2
  │ │ │ ├── safe-buffer@5.1.2
  │ │ │ ├── tough-cookie@2.3.4 extraneous
  │ │ │ ├─┬ tunnel-agent@0.6.0
  │ │ │ │ └── safe-buffer@5.1.2 deduped
  │ │ │ └── uuid@3.2.1
  │ │ ├── sax@1.2.4
  │ │ ├── symbol-tree@3.2.2
  │ │ ├─┬ tough-cookie@2.4.2
  │ │ │ ├── psl@1.1.27
  │ │ │ └── punycode@1.4.1
  │ │ ├── webidl-conversions@2.0.1
  │ │ ├─┬ whatwg-url-compat@0.6.5
  │ │ │ └── tr46@0.0.3
  │ │ └── xml-name-validator@2.0.1
  │ ├── mathjax@2.7.4
  │ ├─┬ speech-rule-engine@2.2.1
  │ │ ├── commander@2.15.1
  │ │ ├── wicked-good-xpath@1.3.0
  │ │ ├─┬ xml-mapping@1.7.1
  │ │ │ ├── sax@0.4.2 extraneous
  │ │ │ └── xml-writer@1.7.0
  │ │ └── xmldom-sre@0.1.31
  │ └─┬ yargs@3.32.0
  │   ├── camelcase@2.1.1
  │   ├─┬ cliui@3.2.0
  │   │ ├── string-width@1.0.2 deduped
  │   │ ├── strip-ansi@3.0.1 deduped
  │   │ └─┬ wrap-ansi@2.1.0
  │   │   ├── string-width@1.0.2 deduped
  │   │   └── strip-ansi@3.0.1 deduped
  │   ├── decamelize@1.2.0
  │   ├─┬ os-locale@1.4.0
  │   │ └─┬ lcid@1.0.0
  │   │   └── invert-kv@1.0.0
  │   ├─┬ string-width@1.0.2
  │   │ ├── code-point-at@1.1.0
  │   │ ├─┬ is-fullwidth-code-point@1.0.0
  │   │ │ └── number-is-nan@1.0.1
  │   │ └── strip-ansi@3.0.1 deduped
  │   ├── window-size@0.1.4
  │   └── y18n@3.2.1
  ├── minimist@1.2.0
  ├─┬ update-notifier@0.6.3
  │ ├─┬ boxen@0.3.1
  │ │ ├── chalk@1.1.3 deduped
  │ │ ├── filled-array@1.1.0
  │ │ ├── object-assign@4.1.1
  │ │ ├─┬ repeating@2.0.1
  │ │ │ └─┬ is-finite@1.0.2
  │ │ │   └── number-is-nan@1.0.1 deduped
  │ │ ├── string-width@1.0.2 deduped
  │ │ └─┬ widest-line@1.0.0
  │ │   └── string-width@1.0.2 deduped
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.1.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1 deduped
  │ │ └── supports-color@2.0.0
  │ ├─┬ configstore@2.1.0
  │ │ ├─┬ dot-prop@3.0.0
  │ │ │ └── is-obj@1.0.1
  │ │ ├── graceful-fs@4.1.11
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8 extraneous
  │ │ ├── object-assign@4.1.1 deduped
  │ │ ├── os-tmpdir@1.0.2
  │ │ ├─┬ osenv@0.1.5
  │ │ │ ├── os-homedir@1.0.2
  │ │ │ └── os-tmpdir@1.0.2 deduped
  │ │ ├── uuid@2.0.3 extraneous
  │ │ ├─┬ write-file-atomic@1.3.4
  │ │ │ ├── graceful-fs@4.1.11 deduped
  │ │ │ ├── imurmurhash@0.1.4
  │ │ │ └── slide@1.1.6
  │ │ └─┬ xdg-basedir@2.0.0
  │ │   └── os-homedir@1.0.2 deduped
  │ ├── is-npm@1.0.0
  │ ├─┬ latest-version@2.0.0
  │ │ └─┬ package-json@2.4.0
  │ │   ├─┬ got@5.7.1
  │ │   │ ├─┬ create-error-class@3.0.2
  │ │   │ │ └── capture-stack-trace@1.0.0
  │ │   │ ├─┬ duplexer2@0.1.4
  │ │   │ │ └── readable-stream@2.3.6 deduped
  │ │   │ ├── is-redirect@1.0.0
  │ │   │ ├── is-retry-allowed@1.1.0
  │ │   │ ├── is-stream@1.1.0
  │ │   │ ├── lowercase-keys@1.0.1
  │ │   │ ├── node-status-codes@1.0.0
  │ │   │ ├── object-assign@4.1.1 deduped
  │ │   │ ├─┬ parse-json@2.2.0
  │ │   │ │ └─┬ error-ex@1.3.1
  │ │   │ │   └── is-arrayish@0.2.1
  │ │   │ ├─┬ pinkie-promise@2.0.1
  │ │   │ │ └── pinkie@2.0.4
  │ │   │ ├─┬ read-all-stream@3.1.0
  │ │   │ │ ├── pinkie-promise@2.0.1 deduped
  │ │   │ │ └── readable-stream@2.3.6 deduped
  │ │   │ ├─┬ readable-stream@2.3.6
  │ │   │ │ ├── core-util-is@1.0.2
  │ │   │ │ ├── inherits@2.0.3
  │ │   │ │ ├── isarray@1.0.0
  │ │   │ │ ├── process-nextick-args@2.0.0
  │ │   │ │ ├── safe-buffer@5.1.2 deduped
  │ │   │ │ ├─┬ string_decoder@1.1.1
  │ │   │ │ │ └── safe-buffer@5.1.2 deduped
  │ │   │ │ └── util-deprecate@1.0.2
  │ │   │ ├── timed-out@3.1.3
  │ │   │ ├── unzip-response@1.0.2
  │ │   │ └─┬ url-parse-lax@1.0.0
  │ │   │   └── prepend-http@1.0.4
  │ │   ├─┬ registry-auth-token@3.3.2
  │ │   │ ├─┬ rc@1.2.8
  │ │   │ │ ├── deep-extend@0.6.0
  │ │   │ │ ├── ini@1.3.5
  │ │   │ │ ├── minimist@1.2.0 deduped
  │ │   │ │ └── strip-json-comments@2.0.1
  │ │   │ └── safe-buffer@5.1.2 deduped
  │ │   ├─┬ registry-url@3.1.0
  │ │   │ └── rc@1.2.8 deduped
  │ │   └── semver@5.5.0 deduped
  │ └─┬ semver-diff@2.1.0
  │   └── semver@5.5.0
  ├─┬ utils-copy@1.1.1
  │ ├── const-pinf-float64@1.0.0
  │ ├── object-keys@1.0.11
  │ ├── type-name@2.0.2
  │ ├─┬ utils-copy-error@1.0.1
  │ │ ├── object-keys@1.0.11 deduped
  │ │ └── utils-copy@1.1.1 deduped
  │ ├─┬ utils-indexof@1.0.0
  │ │ ├─┬ validate.io-array-like@1.0.2
  │ │ │ ├── const-max-uint32@1.0.2
  │ │ │ └── validate.io-integer-primitive@1.0.0 deduped
  │ │ └─┬ validate.io-integer-primitive@1.0.0
  │ │   └── validate.io-number-primitive@1.0.0
  │ ├─┬ utils-regex-from-string@1.0.0
  │ │ ├── regex-regex@1.0.0
  │ │ └── validate.io-string-primitive@1.0.1 deduped
  │ ├── validate.io-array@1.0.6
  │ ├── validate.io-buffer@1.0.2
  │ └─┬ validate.io-nonnegative-integer@1.0.0
  │   └── validate.io-integer@1.0.5 deduped
  ├── validate.io-boolean-primitive@1.0.0
  ├── validate.io-function@1.0.2
  ├─┬ validate.io-object@1.0.4
  │ └── validate.io-array@1.0.6 deduped
  ├─┬ validate.io-positive-integer@1.0.0
  │ └─┬ validate.io-integer@1.0.5
  │   └── validate.io-number@1.0.3
  └── validate.io-string-primitive@1.0.1
```

**Comment by Dupplicate** [comment]
Seems to be a deprecated API mathjax is using.

I hacked this away by changeing
`.../lib/node_modules/tex-equation-to-svg/node_modules/mathjax-node/lib/mj-single.js` in line 540 "`processExpression`" into "`toSpeech`".
